### 텐서플로우 실행하기

In [1]:
import tensorflow as tf

In [2]:
hello = tf.constant('hello tensorflow!') # tf.constant() : 상수 만들기 -> 변하지 않는 값
print(hello)

sess=tf.Session()
result=sess.run(hello)
print(result)
sess.close()

Tensor("Const:0", shape=(), dtype=string)
b'hello tensorflow!'


### 계산 그래프 만들기

In [3]:
import tensorflow as tf

# 노드 만들기
node1=tf.constant(3, tf.float32) # node1과 node2의 형태가 같아야 계산이 가능함
node2=tf.constant(4.0)
node3=tf.add(node1,node2) # 엣지까지 같이 만들기

In [4]:
# node1, node2, node3 은 텐서 노드일뿐
print("node1:", node1)
print("node2:", node2)
print("node3:", node3)

node1: Tensor("Const_1:0", shape=(), dtype=float32)
node2: Tensor("Const_2:0", shape=(), dtype=float32)
node3: Tensor("Add:0", shape=(), dtype=float32)


In [5]:
session=tf.Session()
print("session.run([node1,node2]):", session.run([node1,node2]))
print("session.run(node3)", session.run(node3))

session.close() # session을 열었으면 닫아줘야함(파일처럼)

session.run([node1,node2]): [3.0, 4.0]
session.run(node3) 7.0


### 상수형

In [6]:
# 다른 type으로 / 1bite=8bit
a=tf.constant(1, dtype=tf.float32) # float는 실수 -> float32는 2의 32승개의 실수를 표현할 수 있다는 것 
print(a)
print(a.shape)   # shape 이 없다 -> 차원이 없다 -> 스칼라
with tf.Session() as session:
    print(session.run(a))

Tensor("Const_3:0", shape=(), dtype=float32)
()
1.0


In [7]:
# 다른 shape으로
a=tf.constant(1,dtype=tf.float32, shape=(1,))
print(a)
print(a.shape) # 여기서 a의 shape은 1차원인 벡터
with tf.Session() as session:
    print(session.run(a))

Tensor("Const_4:0", shape=(1,), dtype=float32)
(1,)
[1.]


In [8]:
# 2차원으로 설정
a=tf.constant(1,dtype=tf.float32, shape=(1,1))
print(a)
print(a.shape)  
with tf.Session() as session:
    print(session.run(a))

Tensor("Const_5:0", shape=(1, 1), dtype=float32)
(1, 1)
[[1.]]


### Placeholder : 갈아끼울수 있는 값

In [10]:
import tensorflow as tf

input_data=[1,2,3]
x=tf.placeholder(dtype=tf.float32)  # x는 어떠한 값도 아님
y=x*2
print("x: ",x)
print("y: ",y)

session=tf.Session()

# feed_dict를 통해 값을 전달
result=session.run(y,feed_dict={x:input_data})
print(result)
session.close()

# 결과에서 2. 4. 6. 으로 나오는 이유는 x가 실수형이기 때문

x:  Tensor("Placeholder_1:0", dtype=float32)
y:  Tensor("mul_1:0", dtype=float32)
[2. 4. 6.]


### Variable

In [11]:
x=tf.placeholder(dtype=tf.float32)
x_data=[1,2,4]

# 초기값 : tf.random_normal([1,3], stddev=0.35)
weights=tf.Variable([3], dtype=tf.float32)
biases=tf.Variable([4], dtype=tf.float32)

y= weights*x + biases

print("x: ", x)
print("weights: ", weights)
print("biases: ", biases)

x:  Tensor("Placeholder_2:0", dtype=float32)
weights:  <tf.Variable 'Variable:0' shape=(1,) dtype=float32_ref>
biases:  <tf.Variable 'Variable_1:0' shape=(1,) dtype=float32_ref>


### 개별 initializer

In [12]:
with tf.Session() as session:
    # 초기화 오퍼레이션을 실행
    session.run([weights.initializer, biases.initializer])   # list로 run할 수 있음
    
    result=session.run(y, feed_dict={x:x_data})
    print(result)
    
    # 변수 변경 // 변수 재할당
    session.run(tf.assign(weights, [2]))
    
    # 다시 실행
    result=session.run(y,feed_dict={x:x_data})
    print(result)

[ 7. 10. 16.]
[ 6.  8. 12.]


### 전체 변수 한번에 초기화 - global_variables_initializer

In [14]:
# 변수 초기화 작업
init_op=tf.global_variables_initializer()

with tf.Session() as session:
    # 초기화 오퍼레이션을 실행
    session.run(init_op)
    
    result=session.run(y, feed_dict={x:x_data})
    print(result)
    
    # 변수 변경 // 변수 재할당
    session.run(tf.assign(weights, [2]))
    
    # 다시 실행
    result=session.run(y, feed_dict={x:x_data})
    print(result)

[ 7. 10. 16.]
[ 6.  8. 12.]
